name: Update uv lockfiles

on:
  schedule:
    - cron: '0 12 1 * *'

  workflow_dispatch:

jobs:
  update:
    uses: glotzerlab/workflows/.github/workflows/update-uv-lockfiles.yaml@a36a97114c60241b26217ce92abbb64621ac67c7 # 0.6.0
    secrets: inherit
    with:
      branch: master
